compiler = g++

compile_flags = -Wall -Werror -Wpedantic

build_dir = build/
include_dir = include/
src_dir = src/

src_files = $(wildcard: $(src-dir)/*.c)
target = algo_lang

$(build_dir)/$(target):
	$(compiler) $(compile_flags) $(src_files) -o $@

clean:
	rm -rf $(build_dir)

.PHONY: $(build_dir)/$(target) clean
